<a href="https://colab.research.google.com/github/arthur422tp/arthur422/blob/master/%E3%80%8C%E5%B0%88%E6%A1%88_ipynb%E3%80%8D(%E6%9C%AC%E7%89%A9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
import requests
import bs4
import pandas as pd
from sklearn import linear_model
import numpy as np
import sklearn.preprocessing
!pip install statsmodels

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [101]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [102]:
data_1 = pd.read_excel('/content/drive/MyDrive/桃園樂天.xlsx')
data_2 = pd.read_excel('/content/drive/MyDrive/桃園樂天.xlsx',sheet_name= '工作表2')
data_combine = pd.read_excel('/content/drive/MyDrive/桃園樂天.xlsx',sheet_name= '工作表4')


In [103]:
df_frame_1 = pd.DataFrame(data_1)
df_frame_2 = pd.DataFrame(data_2)
df_frame_data = pd.DataFrame(data_combine)

In [104]:
df_frame_data

場次         日期   星期  球場        客隊(全壘打)(失誤) 主隊(全壘打)(失誤)   觀眾人數  襄  苡  妲  \
0     35 2021-04-03  (六)  桃園         中信兄弟(1)(1)  樂天桃猿(0)(1)  11513  0  0  1   
1    258 2021-11-13  (六)  桃園  統一7-ELEVEn獅(0)(2)  樂天桃猿(0)(0)  10133  1  0  0   
2     60 2021-04-17  (六)  桃園         中信兄弟(2)(1)  樂天桃猿(1)(1)   9378  1  1  1   
3     37 2021-04-04  (日)  桃園         富邦悍將(0)(2)  樂天桃猿(0)(2)   8395  1  0  0   
4     16 2021-03-23  (二)  桃園          味全龍(1)(0)  樂天桃猿(0)(1)   7884  1  1  0   
..   ...        ...  ...  ..                ...         ...    ... .. .. ..   
103   63 2022-05-10  (二)  桃園         富邦悍將(0)(2)  樂天桃猿(0)(0)   3662  0  1  1   
104   27 2022-05-09  (一)  桃園         富邦悍將(0)(0)  樂天桃猿(0)(0)   3632  0  1  0   
105   31 2022-04-21  (四)  桃園  統一7-ELEVEn獅(0)(0)  樂天桃猿(0)(1)   3621  1  0  1   
106  247 2022-09-13  (二)  桃園         中信兄弟(2)(1)  樂天桃猿(0)(1)   3540  0  1  0   
107   29 2022-04-20  (三)  桃園  統一7-ELEVEn獅(0)(1)  樂天桃猿(1)(2)   3038  0  0  0   

                                                    女孩  Unnamed: 11  \
0    4/3  沐曲     鹿妲 芯舞      璐   凱孟        筠宣     紫霓...          NaN   
1    11/13沐曲慧   鹿     舞        籃          菲 筠   伊襄 ...          NaN   
2    4/17     慧     妲 芯舞   苡 璐        潼叡菲   宣 伊襄  霓...          NaN   
3    4/4  沐  慧   鹿     舞卉    璐   凱孟     菲 筠宣 伊襄    ...          NaN   
4    3/23   曲  倪 鹿       卉 苡   籃   孟     菲 筠   伊襄紫霓...          NaN   
..                                                 ...          ...   
103  5/10 曲  倪 縈妲   舞   苡 籃          菲        紫  樂 ...          NaN   
104  5/9  曲     縈   芯舞   苡                   伊    霓...          NaN   
105  4/21   慧     妲   舞         凱孟 潼  菲 筠 伊襄    樂  ...          NaN   
106  9/13 曲慧倪        舞卉 苡 籃 凱孟     菲               ...          NaN   
107  4/20 曲     縈   芯舞卉 苡                筠 伊  紫    ...          NaN   

    Unnamed: 12  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN  
..          ...  
103         NaN  
104         NaN  
105         NaN  
106         阿迷趴  
107         NaN  

[108 rows x 13 columns]

In [105]:
from sklearn.linear_model import LogisticRegression

In [106]:
interest_columns = ['襄', '苡', '妲']
X1 = df_frame_1[interest_columns]
X2 = df_frame_2[interest_columns]
X = df_frame_data[interest_columns]

In [107]:
Y1 = df_frame_1[['觀眾人數']]
Y2 = df_frame_2[['觀眾人數']]
Y = df_frame_data[['觀眾人數']]

In [108]:
threshold = 3180  # 以 10 為閾值進行二元分類
Y1 = np.where(Y1 >= threshold, 1, 0)

In [109]:
threshold = 4903  # 以 10 為閾值進行二元分類
Y2 = np.where(Y2 >= threshold, 1, 0)

In [110]:
Y_ = np.vstack((Y1, Y2))
print(Y_)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [111]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_, test_size=0.2, random_state=42)

In [112]:
print(X_train)

     襄  苡  妲
64   0  1  1
26   0  0  1
22   1  0  1
31   1  1  1
47   0  0  1
..  .. .. ..
71   0  0  1
14   0  0  1
92   1  0  1
51   0  1  0
102  1  1  0

[86 rows x 3 columns]


In [113]:
print('Samples of X:', X_train[:5])
print('Sample of Y:', Y_train[:5])

Samples of X:     襄  苡  妲
64  0  1  1
26  0  0  1
22  1  0  1
31  1  1  1
47  0  0  1
Sample of Y: [[1]
 [0]
 [1]
 [0]
 [0]]


In [114]:
X_train.shape

(86, 3)

In [115]:
Y_train.shape

(86, 1)

In [116]:
print(Y_test)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]]


In [117]:
print(Y_train)

[[1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]]


In [118]:
# 將連續型目標變數轉換為二元類別標籤
#threshold = 4041.5  # 以 10 為閾值進行二元分類
#Y_train = np.where(Y_train >= threshold, 1, 0)

In [119]:
#threshold = 4041.5  # 以 10 為閾值進行二元分類

#Y_test = np.where(Y_test >= threshold, 1, 0)

In [120]:
# 1: 建立 logistic regression 模型
model_logreg = LogisticRegression()

# 訓練模型
model_logreg.fit(X_train, Y_train)



# 2: 預測測試集的機率
y_pred = model_logreg.predict(X_test)

# 3. 檢查係數
print('B0 of LR', model_logreg.intercept_)
print('B1 of LR', model_logreg.coef_)
model_logreg.get_params(deep = True)

B0 of LR [-0.28464984]
B1 of LR [[-0.06639942  0.59142736  1.00592238]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [121]:
len(y_pred)

22

In [122]:
from sklearn.metrics import mean_squared_error

#先看訓練集的分數
y_pred_train = model_logreg.predict(X_train_scaled)
print('Official of RSS [training set]:', mean_squared_error(Y_train, y_pred_train) * len(Y_train))
print('模型分數[training set]:',model_logreg.score(X_train, Y_train))



Official of RSS [training set]: 32.0
模型分數[training set]: 0.6627906976744186


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [123]:
print('Official of RSS:', mean_squared_error(Y_test, y_pred) * len(Y_test))
print('模型分數:',model_logreg.score(X_test, Y_test))

Official of RSS: 7.0
模型分數: 0.6818181818181818


In [124]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.33      0.17      0.22         6
           1       0.74      0.88      0.80        16

    accuracy                           0.68        22
   macro avg       0.54      0.52      0.51        22
weighted avg       0.63      0.68      0.64        22



In [125]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

# 打印混淆矩陣
print("Confusion Matrix:")
print(cm)


Confusion Matrix:
[[ 1  5]
 [ 2 14]]


#考慮到我們想要分析的是模型的係數，sklearn默認使用正則化回歸，會使得係數產生偏差，因此做了version2

#使用statsmodel.api建立logistic模型，並加以分析


In [127]:
import statsmodels.api as sm

# 建立羅吉斯回歸模型
logit_model = sm.Logit(Y_train, X_train)

# 訓練模型
logit_result = logit_model.fit()

# 檢視模型摘要
print(logit_result.summary())

Optimization terminated successfully.
         Current function value: 0.626291
         Iterations 5
                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                   86
Model:                          Logit   Df Residuals:                       83
Method:                           MLE   Df Model:                            2
Date:                Fri, 02 Jun 2023   Pseudo R-squ.:                 0.06674
Time:                        08:51:03   Log-Likelihood:                -53.861
converged:                       True   LL-Null:                       -57.713
Covariance Type:            nonrobust   LLR p-value:                   0.02124
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
襄             -0.2930      0.443     -0.661      0.509      -1.162       0.576
苡              0.4850      0.

In [149]:
Y_pred = logit_result.predict(X_test)
Y_pred_binary = (Y_pred >= 0.5).astype(int)

In [147]:
Y_pred_binary = Y_pred_binary.values

In [148]:
accuracy = (Y_pred_binary == Y_test).mean()
print("准确率：", accuracy)

准确率： 0.7066115702479339


In [128]:
logit_result.params

襄   -0.292984
苡    0.484962
妲    0.974992
dtype: float64

In [129]:
np.exp(logit_result.params)

襄    0.746034
苡    1.624113
妲    2.651145
dtype: float64

In [130]:
params = logit_result.params
conf_ = logit_result.conf_int()
conf_['Odds Ratios'] = params
conf_.columns = ["5%","95%","Odds Ratios"]
print(np.exp(conf_))

         5%       95%  Odds Ratios
襄  0.312842  1.779069     0.746034
苡  0.745538  3.538043     1.624113
妲  1.207598  5.820293     2.651145
